
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 16;
  public static final int IDENTIFIER = 110;
  public static final int ANDEQ = 102;
  public static final int GT = 82;
  public static final int IMPLEMENTS = 48;
  public static final int CONST = 113;
  public static final int STRICTFP = 112;
  public static final int HELLO = 4;
  public static final int NOTEQ = 87;
  public static final int PLUSEQ = 97;
  public static final int RBRACK = 23;
  public static final int CATCH = 67;
  public static final int COMMA = 27;
  public static final int RBRACE = 29;
  public static final int THROW = 65;
  public static final int RPAREN = 32;
  public static final int LBRACK = 22;
  public static final int LT = 81;
  public static final int ANDAND = 91;
  public static final int OROR = 92;
  public static final int LOCATION = 11;
  public static final int DOUBLE = 21;
  public static final int LBRACE = 28;
  public static final int TRANSIENT = 44;
  public static final int LPAREN = 31;
  public static final int XOREQ = 103;
  public static final int PROTECTED = 37;
  public static final int INTEGER_LITERAL = 105;
  public static final int NOT = 75;
  public static final int USERNAME = 12;
  public static final int FINAL = 41;
  public static final int FLOAT = 20;
  public static final int GOTO = 114;
  public static final int URSHIFTEQ = 101;
  public static final int PACKAGE = 34;
  public static final int COMP = 74;
  public static final int EQ = 30;
  public static final int BOOLEAN_LITERAL = 107;
  public static final int MOD = 77;
  public static final int CLASS = 46;
  public static final int SUPER = 52;
  public static final int ABSTRACT = 40;
  public static final int WS = 2;
  public static final int NATIVE = 42;
  public static final int PLUS = 72;
  public static final int LONG = 18;
  public static final int QUESTION = 93;
  public static final int WHILE = 60;
  public static final int EXTENDS = 47;
  public static final int NICE = 5;
  public static final int INTERFACE = 53;
  public static final int CHAR = 19;
  public static final int BOOLEAN = 14;
  public static final int SWITCH = 56;
  public static final int DO = 59;
  public static final int FOR = 61;
  public static final int RSHIFTEQ = 100;
  public static final int DIV = 76;
  public static final int VOID = 49;
  public static final int PUBLIC = 36;
  public static final int RETURN = 64;
  public static final int MULT = 26;
  public static final int ELSE = 55;
  public static final int TRY = 66;
  public static final int GTEQ = 84;
  public static final int BREAK = 62;
  public static final int DOT = 24;
  public static final int INT = 17;
  public static final int CLOCK = 10;
  public static final int NULL_LITERAL = 111;
  public static final int THROWS = 50;
  public static final int STRING_LITERAL = 109;
  public static final int EQEQ = 86;
  public static final int EOF = 0;
  public static final int SEMICOLON = 25;
  public static final int WHERE = 6;
  public static final int THIS = 51;
  public static final int DEFAULT = 58;
  public static final int PRINT = 9;
  public static final int MULTEQ = 94;
  public static final int IMPORT = 35;
  public static final int MINUS = 73;
  public static final int CM = 3;
  public static final int LTEQ = 83;
  public static final int OS = 13;
  public static final int OR = 90;
  public static final int URSHIFT = 80;
  public static final int error = 1;
  public static final int SYNCHRONIZED = 43;
  public static final int DIVEQ = 95;
  public static final int LSHIFTEQ = 99;
  public static final int FINALLY = 68;
  public static final int CONTINUE = 63;
  public static final int INSTANCEOF = 85;
  public static final int IF = 54;
  public static final int MODEQ = 96;
  public static final int MINUSMINUS = 71;
  public static final int END = 8;
  public static final int COLON = 33;
  public static final int CHARACTER_LITERAL = 108;
  public static final int OREQ = 104;
  public static final int VOLATILE = 45;
  public static final int BEGIN = 7;
  public static final int CASE = 57;
  public static final int PLUSPLUS = 70;
  public static final int NEW = 69;
  public static final int RSHIFT = 79;
  public static final int BYTE = 15;
  public static final int AND = 88;
  public static final int PRIVATE = 38;
  public static final int STATIC = 39;
  public static final int LSHIFT = 78;
  public static final int XOR = 89;
  public static final int FLOATING_POINT_LITERAL = 106;
  public static final int MINUSEQ = 98;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "WS",
  "CM",
  "HELLO",
  "NICE",
  "WHERE",
  "BEGIN",
  "END",
  "PRINT",
  "CLOCK",
  "LOCATION",
  "USERNAME",
  "OS",
  "BOOLEAN",
  "BYTE",
  "SHORT",
  "INT",
  "LONG",
  "CHAR",
  "FLOAT",
  "DOUBLE",
  "LBRACK",
  "RBRACK",
  "DOT",
  "SEMICOLON",
  "MULT",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "EQ",
  "LPAREN",
  "RPAREN",
  "COLON",
  "PACKAGE",
  "IMPORT",
  "PUBLIC",
  "PROTECTED",
  "PRIVATE",
  "STATIC",
  "ABSTRACT",
  "FINAL",
  "NATIVE",
  "SYNCHRONIZED",
  "TRANSIENT",
  "VOLATILE",
  "CLASS",
  "EXTENDS",
  "IMPLEMENTS",
  "VOID",
  "THROWS",
  "THIS",
  "SUPER",
  "INTERFACE",
  "IF",
  "ELSE",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "DO",
  "WHILE",
  "FOR",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "THROW",
  "TRY",
  "CATCH",
  "FINALLY",
  "NEW",
  "PLUSPLUS",
  "MINUSMINUS",
  "PLUS",
  "MINUS",
  "COMP",
  "NOT",
  "DIV",
  "MOD",
  "LSHIFT",
  "RSHIFT",
  "URSHIFT",
  "LT",
  "GT",
  "LTEQ",
  "GTEQ",
  "INSTANCEOF",
  "EQEQ",
  "NOTEQ",
  "AND",
  "XOR",
  "OR",
  "ANDAND",
  "OROR",
  "QUESTION",
  "MULTEQ",
  "DIVEQ",
  "MODEQ",
  "PLUSEQ",
  "MINUSEQ",
  "LSHIFTEQ",
  "RSHIFTEQ",
  "URSHIFTEQ",
  "ANDEQ",
  "XOREQ",
  "OREQ",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "BOOLEAN_LITERAL",
  "CHARACTER_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "NULL_LITERAL",
  "STRICTFP",
  "CONST",
  "GOTO"
  };
}

